services:
  web:
    image: test
    restart: always
    env_file:
      - path: .env
        required: false
    command: paon
    environment:
      BIND: 0.0.0.0
      PORT: 3000
      PAON_PROCESS_ROLE: web
      PAON_PUBLIC_DIR: /opt/mastodon/public
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget -q --spider --proxy=off localhost:3000/health/ready || exit 1',
        ]
    ports:
      - '3000:3000'
    volumes:
      - ./public/system:/opt/mastodon/public/system

  worker:
    image: test
    restart: always
    env_file:
      - path: .env
        required: false
    command: paon
    environment:
      PAON_PROCESS_ROLE: worker
      PAON_PUBLIC_DIR: /opt/mastodon/public
    healthcheck:
      disable: true
    volumes:
      - ./public/system:/opt/mastodon/public/system
