export const NOTIFICATION_GROUPS_FETCH_REQUEST =
  'NOTIFICATION_GROUPS_FETCH_REQUEST';
export const NOTIFICATION_GROUPS_FETCH_SUCCESS =
  'NOTIFICATION_GROUPS_FETCH_SUCCESS';
export const NOTIFICATION_GROUPS_FETCH_FAIL = 'NOTIFICATION_GROUPS_FETCH_FAIL';
export const NOTIFICATION_GROUPS_PROCESS_NEW =
  'NOTIFICATION_GROUPS_PROCESS_NEW';
export const NOTIFICATION_GROUPS_LOAD_PENDING =
  'NOTIFICATION_GROUPS_LOAD_PENDING';
export const NOTIFICATION_GROUPS_SCROLL = 'NOTIFICATION_GROUPS_SCROLL';
export const NOTIFICATION_GROUPS_MARK_READ = 'NOTIFICATION_GROUPS_MARK_READ';
export const NOTIFICATION_GROUPS_MOUNT = 'NOTIFICATION_GROUPS_MOUNT';
export const NOTIFICATION_GROUPS_UNMOUNT = 'NOTIFICATION_GROUPS_UNMOUNT';
export const NOTIFICATION_GROUPS_CLEAR_LOCAL =
  'NOTIFICATION_GROUPS_CLEAR_LOCAL';
export const NOTIFICATION_GROUP_DISMISS_LOCAL =
  'NOTIFICATION_GROUP_DISMISS_LOCAL';
export const NOTIFICATION_GROUPS_MERGED = 'NOTIFICATION_GROUPS_MERGED';
